### ISSUE TITLE
fix(ci): invalid `dependabot.yml` configuration

### ISSUE THREAD

**Issue by beatrizsmerino** [beatrizsmerino/nuxt-course#389]
# fix(ci): invalid `dependabot.yml` configuration

| ⏱️ Estimate | 📊 Priority | 📏 Size | 📅 Start | 📅 End |
| --- | --- | --- | --- | --- |
| 1h | P0 | XS | 12-04-2026 | 09-05-2026 |

## 📸 Screenshots

| Current | Expected |
| :---: | :---: |
| <img width="400" alt="GitHub Dependabot configuration error notification for dependabot.yml" src="https://github.com/beatrizsmerino/nuxt-course/assets/14045148/693d3292-f0e8-42be-8ea7-5da65d99e608" /> | N/A — This change has no visual impact. |

## 📝 Summary

- The `dependabot.yml` configuration file has a syntax or configuration error that prevents Dependabot from running correctly
- The error needs to be identified and fixed so Dependabot can automatically create PRs for dependency updates

## 💡 Why this bug?

> [!CAUTION]
> ```
> The configuration file has errors:
> - The property "exclude" is not allowed for commit-message
> - The property "custom-message" is not allowed for commit-message
> - "include" must be a string, not an array
> ```

- The `dependabot.yml` file uses invalid `commit-message` options: `exclude`, `custom-message` and `include: ["*"]`
- GitHub shows an error notification when the Dependabot configuration is invalid

## ✅ Expected behavior

- Dependabot should parse the configuration file without errors
- Dependabot should automatically create PRs for outdated dependencies based on the configured schedule

### Phase 1: Identify invalid `commit-message` options
- [x] Check the GitHub Dependabot error notification to identify the specific issue
- [x] Review the `.github/dependabot.yml` file for YAML syntax errors
- [x] Identify invalid `commit-message` options: `exclude`, `custom-message` and `include: ["*"]` are not supported

### Phase 2: Fix `commit-message` configuration
- [x] Fix `commit-message` configuration in both `npm` and `github-actions` sections:

```diff
     commit-message:
-      prefix: NPM. Upgrade
-      prefix-development: NPM. Upgrade
-      include: ["*"]
-      exclude: ["scope"]
-      custom-message: " from {{from_version}} to {{to_version}}"
+      prefix: fix
+      prefix-development: chore
+      include: scope
```

## 🧪 Tests

- [x] Verify no Dependabot error notification on GitHub
- [x] Confirm Dependabot creates PRs for outdated dependencies
- [x] Check YAML syntax is valid

### Files to modify
- `.github/dependabot.yml`

### Documentation
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
